name: CICD pipeline

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat <<EOF > .env
          POSTGRES_DATABASE_HOST=${{ secrets.POSTGRES_DATABASE_HOST }}
          POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE_PORT=${{ secrets.POSTGRES_DATABASE_PORT }}
          EOF


      - name: Build Docker images
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

